ALL: tcp shm ros shm_ros udp

.PHONY: tcp
tcp:
	make -C tcp -f Makefile.qnx

.PHONY: shm
shm:
	make -C shm -f Makefile.qnx

.PHONY: ros
ros:
	make -C ros -f Makefile.qnx

.PHONY: shm_ros
shm_ros:
	make -C shm_ros -f Makefile.qnx

.PHONY: udp
udp:
	make -C udp -f Makefile.qnx

.PHONY: clean
clean:
	make -C tcp clean
	make -C shm clean
	make -C ros clean
	make -C shm_ros clean
	make -C udp clean
