# !!! You may need to set the below environment variables
#export PATH=$PATH:/opt/qnx700/host/linux/x86_64/usr/bin
#export QNX_HOST=/opt/qnx700/host/linux/x86_64
#export QNX_TARGET=/opt/qnx700/target/qnx7

ALL: pub sub

.PHONY:pub
pub:
	q++ -O3 -g3 -V5.4.0,gcc_ntoaarch64le -o pub pub.cpp  -D__QNX__

.PHONY:sub
sub:
	q++ -O3 -g3 -V5.4.0,gcc_ntoaarch64le -o sub sub.cpp  -D__QNX__

.PHONY:clean
clean:
	rm -rf pub sub
